---
title: "Coronavirus"
author: "Valentin Henriot"
date: "15/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Etude sur les cas de Covid-19 recensés

```{r}
#library(coronavirus)
```

```{r}
#data("coronavirus")
#data("covid_south_korea")
#data("covid_italy")
#data("covid_iran")
```

```{r}
coronavirus <- utils::read.csv("https://raw.githubusercontent.com/RamiKrispin/coronavirus-csv/master/coronavirus_dataset.csv")
```

```{r}
library(dplyr)

summary_df <- coronavirus %>% group_by(Country.Region, type) %>%
  summarise(total_cases = sum(cases)) %>%
  arrange(-total_cases)

summary_df %>% head(20)
```

```{r include=FALSE}
coronavirus$date <- as.Date(coronavirus$date, "%Y-%m-%d")
```

```{r}
library(tidyr)

coronavirus %>% 
  filter(date == max(date)) %>%
  select(country = Country.Region, type, cases) %>%
  group_by(country, type) %>%
  summarise(total_cases = sum(cases)) %>%
  pivot_wider(names_from = type,
              values_from = total_cases) %>%
  arrange(-confirmed)
```

```{r}
CoronavirusFR <- filter(coronavirus, Country.Region == "France")
```

```{r}
CoronavirusFR2 <- filter(CoronavirusFR, Province.State == "France")
```

```{r}
library (ggplot2)
ggplot(CoronavirusFR2) +
 aes(x = date, fill = type, colour = type, weight = cases) +
 geom_bar() +
 scale_fill_hue() +
 scale_color_hue() +
 labs(y = "Nombre de cas", title = "Coronavirus en France", caption = "Source : Rami Krispin dataset coronavirus") +
 ggthemes::theme_stata()
```

```{r}
CoronavirusIT <- filter(coronavirus, Country.Region == "Italy")
```

```{r}
ggplot(CoronavirusIT) +
 aes(x = date, fill = type, colour = type, weight = cases) +
 geom_bar() +
 scale_fill_hue() +
 scale_color_hue() +
 labs(y = "Nombre de cas", title = "Coronavirus en Italie", caption = "Source : Rami Krispin dataset coronavirus") +
 ggthemes::theme_stata()
```

```{r}
CoronavirusDE <- filter(coronavirus, Country.Region == "Germany")
```

```{r}
ggplot(CoronavirusDE) +
 aes(x = date, fill = type, colour = type, weight = cases) +
 geom_bar() +
 scale_fill_hue() +
 scale_color_hue() +
 labs(y = "Nombre de cas", title = "Coronavirus en Allemagne", caption = "Source : Rami Krispin dataset coronavirus") +
 ggthemes::theme_stata()
```

```{r}
CoronavirusSPA <- filter(coronavirus, Country.Region == "Spain")
```

```{r}
ggplot(CoronavirusSPA) +
 aes(x = date, fill = type, colour = type, weight = cases) +
 geom_bar() +
 scale_fill_hue() +
 scale_color_hue() +
 labs(y = "Nombre de cas", title = "Coronavirus en Espagne", caption = "Source : Rami Krispin dataset coronavirus") +
 ggthemes::theme_stata()
```

```{r}
CombineCountries <- filter(coronavirus, Country.Region == "France" | Country.Region == "Spain" | Country.Region == "Germany" | Country.Region == "Italy")
```

```{r}
library(plotly)
CombineGraph <-ggplot(CombineCountries, aes(date, cases))

CombineGraph2 <- CombineGraph + geom_bar(stat = "identity", aes(fill = type)) +
  facet_wrap(~ Country.Region) +
  xlab("Date") + 
  ggtitle("Cas de coronavirus") +
  theme_linedraw()

CombineGraph3 <- CombineGraph2 + theme(axis.title.y = element_blank()) 

CombineGraph3 <- ggplotly(CombineGraph3)
CombineGraph3
```

```{r}
DataCountries <- CombineCountries %>% group_by(Country.Region, type) %>%
  summarise(total_cases = sum(cases)) %>%
  arrange(Country.Region)
```

```{r}
DataCountries2 <- spread(DataCountries, "type", "total_cases")
```

```{r}
DataCountries2$confirmed <- as.numeric(DataCountries2$confirmed)
DataCountries2$death <- as.numeric(DataCountries2$death)
DataCountries2$recovered <- as.numeric(DataCountries2$recovered) 
```

```{r}
DataCountries2$"Ratio death/confirmed" <- DataCountries2$death/DataCountries2$confirmed*100
```

```{r}
library(kableExtra)
kable(DataCountries2) %>%
  kable_styling("striped", full_width = F) %>%
  column_spec(3, bold = T) %>%
  row_spec(1, bold = T, color = "white", background = "blue") %>%
  row_spec(2, bold = T, color = "white", background = "red") %>%
  row_spec(3, bold = T, color = "white", background = "green") %>%
  row_spec(4, bold = T, color = "white", background = "orange")
```

```{r}
library(rdbnomics)
HospitalEmployment <- rdb(ids = c('Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.IT', "Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.FR", "Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.ES", "Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.DE")) %>%
  filter(!is.na(value)) # Annual – Hospital employment – Head count per hundred thousand inhabitants
```

### Faire une courbe cumulative des confirmés et des décédés

```{r}
summary_df2 <- spread(coronavirus, "type", "cases")
```

```{r}
SpreadCountries <- filter(summary_df2, Country.Region == "France" & Province.State == "France" | Country.Region == "Spain" | Country.Region == "Germany" | Country.Region == "Italy") 
```

```{r}
SpreadCountries1 <- SpreadCountries[,-1]
```

```{r}
CountriesConfirmed <- SpreadCountries1 %>% group_by(Country.Region) %>% mutate(CumulConfirmes=cumsum(confirmed))
```

```{r}
ggplot(CountriesConfirmed) +
 aes(x = date, y = CumulConfirmes, colour = Country.Region) +
 geom_line(size = 1L) +
 scale_color_hue() +
 labs(y = "Nombre de cas confirmés (cumulés)", title = "Nombre de personnes infectées par le Covid-19") +
 ggthemes::theme_stata()
```

```{r}
CountriesDeath <- SpreadCountries1 %>% group_by(Country.Region) %>%  mutate(CumulMort=cumsum(death))
```

```{r}
ggplot(CountriesDeath) +
 aes(x = date, y = CumulMort, colour = Country.Region) +
 geom_line(size = 1L) +
 scale_color_hue() +
 labs(y = "Nombre de décès (cumulés)", title = "Décès liés au Covid-19") +
 ggthemes::theme_stata()
```

```{r}
LeftJoin1 <- left_join(CountriesConfirmed, CountriesDeath, by = c("Country.Region", "Lat", "Long", "date", "confirmed", "death", "recovered"))

CountriesRecovered <- SpreadCountries1 %>% group_by(Country.Region) %>%  mutate(CumulSoigne=cumsum(recovered))

LeftJoin2 <- left_join(LeftJoin1, CountriesRecovered, by = c("Country.Region", "Lat", "Long", "date", "confirmed", "death", "recovered"))

LeftJoin2$confirmed <- NULL
LeftJoin2$death <- NULL
LeftJoin2$recovered <- NULL
LeftJoin2$Lat <- NULL
LeftJoin2$Long <- NULL

LeftJoin2$CumulConfirmes <- as.numeric(LeftJoin2$CumulConfirmes)
LeftJoin2$CumulMort <- as.numeric(LeftJoin2$CumulMort)
LeftJoin2$CumulSoigne <- as.numeric(LeftJoin2$CumulSoigne)

FinalCumul <- LeftJoin2 %>% gather(Total, Value, -Country.Region, -date)
```

```{r}
ggplot(FinalCumul) +
 aes(x = date, y = Value, colour = Country.Region, group = Country.Region) +
 geom_line(size = 1L) +
 scale_color_hue() +
 labs(y = "Effectifs cumulés (par catégorie)", title = "Graphique de l'évolution du Covid-19") +
 ggthemes::theme_stata() +
 facet_wrap(vars(Total), scales = "free")
```

```{r}
CombineCumul <-ggplot(FinalCumul, aes(date, Value))

CombineCumul2 <- CombineCumul + geom_bar(stat = "identity", aes(fill = Total)) +
  facet_wrap(~ Country.Region) +
  xlab("Date") + 
  ggtitle("Effectifs cumulés par catégorie de l'évolution du Covid-19") +
  theme_linedraw()

CombineCumul3 <- CombineCumul2 + theme(axis.title.y = element_blank()) 

CombineCumul3 <- ggplotly(CombineCumul3)
CombineCumul3
```

## Etude sur les moyens médicaux

```{r}
library(rdbnomics)
HospitalEmployment <- rdb(ids = c('Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.IT', "Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.FR", "Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.ES", "Eurostat/hlth_rs_prshp1/A.HOSP.HC_HTHAB.DE")) %>%
  filter(!is.na(value)) # Annual – Hospital employment – Head count per hundred thousand inhabitants
```

```{r}
HospitalEmployment2017 <- filter(HospitalEmployment, original_period == 2017)
```

```{r include=FALSE}
base::colnames(HospitalEmployment2017)[colnames(HospitalEmployment2017)=="Geopolitical entity (reporting)"] <- "Country" 
```

```{r include=FALSE}
HospitalEmployment2017$Country <- recode(HospitalEmployment2017$Country,
               "Germany (until 1990 former territory of the FRG)" = "Germany")
```

```{r}
ggplot(HospitalEmployment2017) +
 aes(x = Country, y = value, fill = Country, label = value) +
 geom_col() +
  geom_text(nudge_y = 1) +
 scale_fill_hue() +
 labs(x = "Pays", y = "Ratio pour 100.000 habitants", title = "Nombre d'employés dans les hôpitaux pour 100.000 habitants", caption = "Source : Eurostat (2017)") +
 ggthemes::theme_stata() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
HospitalBeds <- rdb(ids = c('Eurostat/hlth_rs_bds/A.P_HTHAB.HBEDT_CUR.FR', "Eurostat/hlth_rs_bds/A.P_HTHAB.HBEDT_CUR.IT", "Eurostat/hlth_rs_bds/A.P_HTHAB.HBEDT_CUR.ES", "Eurostat/hlth_rs_bds/A.P_HTHAB.HBEDT_CUR.DE")) %>%
  filter(!is.na(value)) # Annual – Per hundred thousand inhabitants – Curative care beds in hospitals 
```

```{r}
HospitalBeds2017 <- filter(HospitalBeds, original_period == 2017)
```

```{r include=FALSE}
base::colnames(HospitalBeds2017)[colnames(HospitalBeds2017)=="Geopolitical entity (reporting)"] <- "Country" 
```

```{r include=FALSE}
HospitalBeds2017$Country <- recode(HospitalBeds2017$Country,
               "Germany (until 1990 former territory of the FRG)" = "Germany")
```

```{r}
ggplot(HospitalBeds2017) +
 aes(x = Country, y = value, fill = Country, label = value) +
 geom_col() +
  geom_text(nudge_y = 1) +
 labs(y = "Ratio pour 100.000 habitants", x = "Pays", title = "Lits d'hôpitaux en soins intensifs pour 100.000 habitants", caption = "Source : Eurostat (2017)") +
 ggthemes::theme_stata() +
  theme(plot.title = element_text(hjust = 0.5))
```

## Etude sur la population

```{r}
TotalPop <- rdb(ids = c('Eurostat/tps00001/A.JAN.FR', "Eurostat/tps00001/A.JAN.IT", "Eurostat/tps00001/A.JAN.ES", "Eurostat/tps00001/A.JAN.DE")) %>%
  filter(!is.na(value)) # Population totale
```

```{r}
TotalPop2019 <- filter(TotalPop, original_period == 2019)
```

```{r}
Pop65andMore <- rdb(ids = c('Eurostat/demo_pjanbroad/A.NR.Y_GE65.T.FR', "Eurostat/demo_pjanbroad/A.NR.Y_GE65.T.IT", "Eurostat/demo_pjanbroad/A.NR.Y_GE65.T.ES", "Eurostat/demo_pjanbroad/A.NR.Y_GE65.T.DE")) %>%
  filter(!is.na(value)) # 65 ans ou plus 
```

```{r}
Pop65andMore2019 <- filter(Pop65andMore, original_period == 2019)
```

```{r}
Country <- c("France", "Italy", "Spain", "Germany")
Ratio <- Pop65andMore2019$value/TotalPop2019$value*100
TableauRatioPop <- data.frame(Country, Ratio) # Ratio 65 ans ou +

colnames(TableauRatioPop)[2] <- "Ratio population > 65 ans"
```

