---
title: "TestMineralWater"
author: "Valentin"
date: "22/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
MineralWater <- read_excel("~/Bootcamp1-DSsignatureTrack/EauxMinérales.xls", col_names = TRUE)
MineralWater
```

```{r}
summary(MineralWater)
```

```{r}
MineralWater$Calcium <- as.numeric(MineralWater$Calcium)
MineralWater$Magnésium <- as.numeric(MineralWater$Magnésium)
MineralWater$Potassium <- as.numeric(MineralWater$Potassium)
MineralWater$Bicarbonates <- as.numeric(MineralWater$Bicarbonates)
MineralWater$Sulfates <- as.numeric(MineralWater$Sulfates)
MineralWater$Fluorures <- as.numeric(MineralWater$Fluorures)
MineralWater$Sodium <- as.numeric(MineralWater$Sodium)
MineralWater$Nitrates <- as.numeric(MineralWater$Nitrates)
MineralWater$`Résidus secs` <- as.numeric(MineralWater$`Résidus secs`)
MineralWater$`Prix/litre` <- as.numeric(MineralWater$`Prix/litre`)
```

```{r}
library(readxl)
MineralWater <- read_excel("~/Bootcamp1-DSsignatureTrack/EauxMinérales.xls")
EauxMinerales_norm <- MineralWater
EauxMinerales_norm[,2:10] <- as.data.frame(apply(EauxMinerales_norm[, 2:10], 2, function(x) (x - min(x))/(max(x)-min(x))))
EauxMinerales_norm
```

```{r}
library(corrplot)
correlationData = cor(EauxMinerales_norm[2:11])
corrplot(correlationData, method = "number")
```

```{r}
library(FactoMineR)
```

```{r}
PCA_MW <- PCA(EauxMinerales_norm[1:11], quali.sup=(1))
```


```{r}
summary(PCA_MW, nbelements = Inf)
```

```{r}
print(EauxMinerales_norm)
```

```{r}
library(factoextra)
pca_biplot <- fviz_pca_biplot(PCA_MW)
pca_biplot
```

```{r}
fviz_eig(PCA_MW, addlabels = TRUE, ylim = c(0, 50))
```

```{r}
var <- get_pca_var(PCA_MW)
var
```

```{r}
head(var$contrib)
```

```{r}
library("corrplot")
corrplot(var$cos2, is.corr=FALSE)
```

```{r}
fviz_pca_var(PCA_MW, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```

```{r}
fviz_pca_ind (PCA_MW, col.ind = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```

