---
title: "New York Test"
author: "Valentin"
date: "03/02/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(readxl)
NYN <- read_excel("NYN.xlsx")
#View(NYN)
```

```{r, include=FALSE}
summary(NYN)
```


```{r, include=FALSE}
library(readxl)
NYN <- read_excel("NYN.xlsx")
NYNnorm <- NYN
NYNnorm[,2:10] <- as.data.frame(apply(NYNnorm[, 2:13], 2, function(x) (x - min(x))/(max(x)-min(x))))
NYNnorm
```

```{r}
library(corrplot)
correlationData = cor(NYNnorm[2:13])
corrplot(correlationData, method = "pie")
```

```{r, include=FALSE}
library(FactoMineR)
```

```{r, include=FALSE}
PCA_NY <- PCA(NYNnorm[1:13], quali.sup = 1)
```


```{r, include=FALSE}
summary(PCA_NY, nbelements = Inf)
```

```{r, include=FALSE}
print(NYNnorm)
```

```{r}
library(factoextra)
pca_biplotNY <- fviz_pca_biplot((PCA_NY), 
repel=TRUE)
pca_biplotNY
```

```{r}
fviz_eig(PCA_NY, addlabels = TRUE, ylim = c(0, 50))
```

```{r, include=FALSE}
varNY <- get_pca_var(PCA_NY)
varNY
```

```{r}
head(varNY$contrib)
```

```{r}
library("corrplot")
corrplot(varNY$cos2, is.corr=FALSE)
```

```{r}
fviz_pca_var(PCA_NY, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```

```{r}
fviz_pca_ind (PCA_NY, col.ind = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```


