---
title: "Le Brésil, puissance régionale ou internationale ?"
author: "Valentin"
date: "08/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(rdbnomics)
library(dplyr)
library(WDI)
```

### Exports extra-MERCOSUR

```{r include=FALSE}
MercosurTradeExt <- rdb(ids = c('WTO/a2/BR.X.GXM.TO', "WTO/a2/AR.X.GXM.TO", "WTO/a2/UY.X.GXM.TO", "WTO/a2/VE.X.GXM.TO")) %>%
  filter(!is.na(value))
MercosurTradeExt
```

```{r}
library(ggplot2)
ggplot(MercosurTradeExt, aes(x = period, y = value, color = series_name)) +
  geom_line(size = 1) + 
  theme(legend.position="bottom") + 
  labs(y = "Valeur en million de $", x = "Année", title = "Exports vers les pays en dehors du MERCOSUR", caption = "Source SKEMA Quantum Studio") +
   guides(col = guide_legend(nrow = 4))
```

### Exports intra-MERCOSUR

```{r include=FALSE}
MercosurTradeInt <- rdb(ids = c('WTO/a2/AR.X.G27.TO', "WTO/a2/BR.X.G27.TO", "WTO/a2/UY.X.G27.TO", "WTO/a2/VE.X.G27.TO")) %>%
  filter(!is.na(value))
MercosurTradeInt
```

```{r}
ggplot(MercosurTradeInt, aes(x = period, y = value, color = series_name)) +
  geom_line(size = 1) + 
  theme(legend.position="bottom") + 
  labs(y = "Valeur en million de $", x = "Année", title = "Exports vers les pays du MERCOSUR", caption = "Source SKEMA Quantum Studio") +
   guides(col = guide_legend(nrow = 4))
```

### Imports extra-MERCOSUR

```{r include=FALSE}
MercosurImportExt <- rdb(ids = c('WTO/a2/AR.M.GXM.TO', "WTO/a2/BR.M.GXM.TO", "WTO/a2/UY.M.GXM.TO", "WTO/a2/VE.M.GXM.TO")) %>%
  filter(!is.na(value))
```

```{r}
ggplot(MercosurImportExt, aes(x = period, y = value, color = series_name)) +
  geom_line(size = 1) + 
  theme(legend.position="bottom") + 
  labs(y = "Valeur en million de $", x = "Année", title = "Imports depuis les pays en dehors du MERCOSUR", caption = "Source SKEMA Quantum Studio") +
   guides(col = guide_legend(nrow = 4))
```

### Imports intra-MERCOSUR

```{r include=FALSE}
MercosurImportInt <- rdb(ids = c('WTO/a2/AR.M.G27.TO', "WTO/a2/BR.M.G27.TO", "WTO/a2/UY.M.G27.TO", "WTO/a2/VE.M.G27.TO")) %>%
  filter(!is.na(value))
MercosurImportInt <- rename(MercosurImportInt, Country = series_name)
```

```{r}
ggplot(MercosurImportInt, aes(x = period, y = value, color = Country)) +
  geom_line(size = 1) + 
  theme(legend.position="bottom") + 
  labs(y = "Valeur en million de $", x = "Année", title = "Imports depuis les pays du MERCOSUR", caption = "Source SKEMA Quantum Studio") +
   guides(col = guide_legend(nrow = 4))
```

### Exports vers les USA

```{r include=FALSE}
MercosurTradeNA <- rdb(ids = c('WTO/a2/AR.X.NAX.TO', "WTO/a2/BR.X.NAX.TO", "WTO/a2/UY.X.NAX.TO", "WTO/a2/VE.X.NAX.TO")) %>%
  filter(!is.na(value)) #export to North America
MercosurTradeNA <- rename(MercosurTradeNA, Country = series_name)
```

```{r}
ggplot(MercosurTradeNA, aes(x = period, y = value, color = Country)) +
  geom_line(size = 1) +
  theme(legend.position="bottom") +
  labs(y = "Valeur en million de $", x = "Année", title = "Exports vers les USA", caption = "Source SKEMA Quantum Studio") +
   guides(col = guide_legend(nrow = 4))
```

### Balance des paiements

```{r}
BalancePaiements <- rdb(ids = c('IMF/BOP/A.AR.BGM_BP6_USD', "IMF/BOP/A.BR.BGM_BP6_USD", "IMF/BOP/A.UY.BGM_BP6_USD", "IMF/BOP/A.VE.BGM_BP6_USD")) %>%
  filter(!is.na(value))
BalancePaiements <- rename(BalancePaiements, Country = "Reference Area")
```

```{r}
ggplot(BalancePaiements, aes(x = period, y = value, color = Country)) +
  geom_line(size = 1) +
  theme(legend.position="bottom") +
  labs(y = "Valeur en million de $", x = "Année", title = "Balance des paiements en Millions de $", caption = "Source SKEMA Quantum Studio") +
   guides(col = guide_legend(nrow = 4))
```

### Analyse de la puissance militaire

```{r include=FALSE}
MilitaryExpenditure <- WDI(indicator = "MS.MIL.XPND.CD", #Military expenditure $
country = c("BRA", "UY", "VE", "ARG"),
                   start = 1996,
                   end = 2017)
MilitaryExpenditure <- rename(MilitaryExpenditure, Military_Expenditure = MS.MIL.XPND.CD)
MilitaryExpenditure
```

```{r include=FALSE}
NbTroops <- WDI(indicator = "MS.MIL.TOTL.P1", #Armed forces personnel, total
country = c("BRA", "UY", "VE", "ARG"),
                   start = 1996,
                   end = 2017)
NbTroops <- rename(NbTroops, Troops = MS.MIL.TOTL.P1)
NbTroops
```

```{r include=FALSE}
TroopsAndExpenditure = bind_cols(MilitaryExpenditure, NbTroops)
TroopsAndExpenditure
```


```{r}
library(plotly)
DynGraphTroopsExp <- ggplot(TroopsAndExpenditure, aes(year, Military_Expenditure, color = country)) +
  geom_point(aes(size = Troops, frame = year)) +
  scale_x_log10() +
  hrbrthemes::theme_modern_rc() +
  labs(y = "Dépenses militaires en $", x = "Année", title = "Comparaison entre dépenses militaires et nombre 
       de militaires", caption = "Source SKEMA Quantum Studio")
DynGraphTroopsExp <- ggplotly(DynGraphTroopsExp)
DynGraphTroopsExp
```

```{r}
PovertyCompare <- rdb(ids = c('UNDATA/DF_UNDATA_WDI/A.MS_MIL_TOTL_TF_ZS.ARG', "UNDATA/DF_UNDATA_WDI/A.MS_MIL_TOTL_TF_ZS.BRA", "UNDATA/DF_UNDATA_WDI/A.MS_MIL_TOTL_TF_ZS.URY", "UNDATA/DF_UNDATA_WDI/A.MS_MIL_TOTL_TF_ZS.VEN")) %>%
  filter(!is.na(value))
PovertyCompare <- rename(PovertyCompare, Country = REF_AREA)
```

```{r}
ggplot(PovertyCompare, aes(x = period, y = value, color = Country)) +
  geom_line(size = 1) +
  theme(legend.position="bottom") +
  labs(y = "Valeur en %", x = "Année", title = "Part des militaires en % du total des travailleurs", caption = "Source SKEMA Quantum Studio") +
   guides(col = guide_legend(nrow = 4))
```

